<?php
// This file is part of Rogo
//
// Rogo is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Rogo is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Rogo.  If not, see <http://www.gnu.org/licenses/>.

require '../lang/' . $language . '/include/months.inc';
require_once '../lang/' . $language . '/paper/new_paper2.php';

$string['moreinformation'] = 'Więcej informacji';
$string['viewdetails'] = 'Ogląd szczegółów';
$string['debuginformation'] = 'Informacje dot. błędów';
$string['loadingdebug'] = 'Wyszukiwanie błędów ładowania';
$string['intermediateformatdebug'] = 'Wyszukiwanie błędów pośrednich';
$string['savingdebug'] = 'Zapisywanie wyników wyszukiwania błędów';
$string['generaldebuginfo'] = 'Ogólne informacje dot. błędów';

$string['addingtopaper'] = 'Dodawanie do arkusza';
$string['params'] = 'Parametry';
$string['othherdebug'] = 'Inne wyszukiwanie błędów';
$string['noquestions'] = 'Brak pytań do załadowania do Rogo';
$string['questiontables'] = 'Tablice pytań';
$string['questionsrow'] = 'wiersze pytań';
$string['optionsrows'] = 'wiersye opcji';
$string['newkeywords'] = 'Nowe słowa kluczowe';
$string['addingquestiondetails'] = 'dodawanie pytania %d jako display_pos = %d na ekranie %d';
?>