<?php
// This file is part of Rogo
//
// Rogo is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Rogo is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Rogo.  If not, see <http://www.gnu.org/licenses/>.

$string['administrativetools'] = 'Narzędzia administracyjne';
$string['helpsupport'] = 'Pomoc i wsparcie';
$string['aboutrogo'] = 'O programie Rog&#333; %s';
$string['html5warn'] = 'Rog&#333; wymaga obsługi HTML5 - uaktualnij swoją przegladarkę.';
$string['furtherassistance'] = 'W celu uzyskania dalszej pomocy skontaktuj się z: <a href="mailto:%s">%s</a>';
$string['pagenotfound'] = 'Strony nie odnaleziono';
$string['signinmsg'] = 'Strona, którą chcesz zobaczyć wymaga uwierzytelnienia. Zaloguj się używając swojej nazwy użytkownika i hasła:';
$string['username'] = 'Nazwa użytkownika';
$string['password'] = 'Hasło';
$string['signin'] = 'Zaloguj się';
$string['signout'] = 'Wyloguj się';
$string['home'] = 'Strona główna';
$string['help'] = 'Pomoc';
$string['line'] = 'Linia';
$string['cancel'] = 'Anuluj';
$string['ok'] = 'OK'; //cognate
$string['save'] = 'Zachowaj';
$string['colours'] = 'Kolory';
$string['new'] = 'Nowy';
$string['old'] = 'Stary';
$string['Objectives Feedback report'] = 'Raport odzewu dot. celów';
$string['Questions Feedback report'] = 'Raport odzewu dot. pytań';
$string['accessdenied'] = 'Brak dostępu';
$string['accessdeniedadmin'] = '<strong>Brak dostępu</strong><br />Podejmujesz działania dostępne tylko administratorowi.';
$string['accessdeniedsysadmin'] = '<strong>Brak dostępu</strong><br />Podejmujesz działania dostępne tylko administratorowi systemu.';
$string['denied_paper'] = 'Nie posiadasz <strong>praw dostępu do tego arkusza</strong>!';
$string['denied_folder'] = 'Nie posiadasz <strong>praw dostępu do tego folderu</strong>!';
$string['denied_question'] = 'Nie posiadasz  <strong>praw dostępu do tego pytania</strong>!';
$string['denied_team'] = 'Nie jesteś członkiem zespołu dla modułu <strong>%s</strong>.';
$string['noldapusernamesupplied'] = 'Nie wprowadzono loginu lub hasła LDAP';
$string['incorrectpassword'] = 'Wprowadzono nieprawidłowe hasło';
$string['ldapserverunavailable'] = 'Serwer LDAP jest niedostępny';
$string['noldapaccount'] = 'Nie odnaleziono konta LDAP !';
$string['ldapservernosearch'] = 'Serwer LDAP niedostępny: wyszukiwanie niemożliwe';
$string['nodatabaseconnection'] = 'Podłączenie do bazy niemożliwe - skontaktuj się z administratorem';
$string['as'] = 'jako';
$string['localtsauthfailed'] = 'Nie uzyskano uwierzytelniania Rogō.';
$string['notsaccount'] = 'Nie odnaleziono konta Rog&#333;!';
$string['tempaccount'] = 'Konto tymczasowe';
$string['authenticationfailed'] = 'Nie uzyskano uwierzytelnienia Rog&#333;, należy pamiętać:';
$string['usernamecasesensitive'] = 'W loginie i haśle rozróżniane są duże i małe litery';
$string['pressf5'] = "Wybierz 'F5' na klawiaturze aby logować się ponownie";
$string['tsonldap'] = 'W Rogō stosowane są hasła LDAP';
$string['ifstuckinvigilator'] = 'W razie dalszych problemów poproś osobę nadzorującą o';
$string['forgottenpassword'] = 'Zapomniane hasło';
$string['warning'] = 'Uwaga:';
$string['secureconnection'] = 'Wymagane bezpieczne połączenie';
$string['secureconnectionmsg'] = 'Rogō jest dostępny wyłącznie przez połączenie bezpieczne. W zamian użyj:';
$string['errormsg'] = 'Jeśli kolejny raz napotkałeś ten błąd skontaktuj się z:';
$string['ltifirstlogin'] = 'Autoryzacja Rogō';
$string['ltifirstlogindesc'] = 'System egzaminowania Rog&#333; wymaga identyfikacji Twojej osoby, aby upewnić się co do posiadanych przez Ciebie przywilejów. Dokonane to będzie tylko przy pierwszej wizycie i w nielicznych przypadkach, w celu zapewnienia bezpieczeństwa w przyszłości.<br /><a href="./">Kliknij, aby kontynuować</a> ';
$string['ltinotconfigured'] = 'Hiperłącze, które wybrałeś nie jest jeszcze skonfigurowane.';
$string['LTIFAILURE'] = 'niepowodzenie LTI';
$string['expiredtimestamp'] = 'Datownik tego połączenia jest już przeterminowany. Powróć do poprzedniej strony i ponownie wybierz ten link (nie odświeżaj przeglądarki).';
$string['UserMissing'] = 'Brak stowarzyszonego użytkownika ';
$string['UserMissingDesc'] = 'Z jakiegoś powodu w systemie Rogo brak jest stowarzyszonego użytkownika. To jest poważny błąd dlatego powinieneś skontaktować się z administratorem systemu';
$string['impersonatepriv'] = 'Nie masz wystarczajacych przywilejów aby podszywać się pod uźytkownika.';  

$string['NoAuthenticationConfigured'] = 'Nie skonfigurowano uwierzytelniania';
$string['NoAuthenticationConfiguredmessage'] = 'Konfiguracja uwierzytelniania nie została wpisana do pliku konfiguracyjnego. Skontaktuj się z administratorem systemu.';
$string['Authentication_callback_failure1'] = 'Nie udało sie zarejestrować wywołania zwrotnego dla sekcji ';
$string['Authentication_callback_failure2'] = ' z funkcją';
$string['Authentication_issue1'] = 'Problemy z uwierzytelnieniem';
$string['Authentication_issue2'] = 'Plugin uwierzytelniania nie zdołał Ciebie zalogować i nie zaoferował żadnego formularza ani przekierowania. Naciśnij F5 aby odświerzyć, a gdy to nie przyniesie poprawy skontaktuj się z administratorem:  <a href="mailto:%s">%s</a>.<p>Załącz do swojego e-maila następujące dane techniczne:</p><div style="margin-left:100px;">%s</div>';
$string['Authentication_issue2nodebug'] = 'Plugin uwierzytelniania nie zdołał Ciebie zalogować i nie zaoferował żadnego formularza ani przekierowania. Naciśnij F5 aby odświerzyć, a gdy to nie przyniesie poprawy skontaktuj się z administratorem:  <a href="mailto:%s">%s</a>.';
$string['Authentication_notloggedin1'] = 'Problemy z uwierzytelnieniem';
$string['Authentication_notloggedin2'] = 'Nie zostałeś zalogowany. Naciśnij F5 aby odświerzyć, a gdy to nie przyniesie poprawy skontaktuj się z administratorem: <a href="mailto:%s">%s</a><p>Załącz do swojego e-maila następujące dane techniczne:</p><div style="margin-left:100px;">%s</div>';
$string['Authentication_notloggedin2nodebug'] = 'Nie zostałeś zalogowany. Naciśnij F5 aby odświerzyć, a gdy to nie przyniesie poprawy skontaktuj się z administratorem: <a href="mailto:%s">%s</a>';
$string['NoLookupConfigured'] = 'Nie skonfigurowano odnośnika';
$string['NoLookupConfiguredmessage'] = 'Konfiguracja odnośnika nie została wpisana do pliku konfiguracyjnego. Skontaktuj się z administratorem systemu.';
$string['guestbutton'] = 'Logowanie gościnne';
$string['authentication_lti_authmessage'] = 'Zaloguj się, aby uwierzytelnić połączenie LTI.';
$string['authentication_lti_reauthmessage'] = 'Zaloguj się, aby ponownie uwierzytelnić połączenie LTI.';
$string['lti_not_allow_add_selfreg'] = 'Automatyczne dodawanie studentów do tego typu modułu nie zostało umożliwione w kofiguracji modułu: '; 

$string['denied_role'] = 'Twoja rola użytkownika - %s - nie daje ci prawa dostępu.';
$string['Error'] = 'Błąd';
$string['NoAcademicSession'] = 'Nie określono sesji akademickiej.';
$string['NoFieldMetadata'] = 'W metadanych brakuje pola dla grup.';
$string['NoGroup'] = 'Nie znaleziono żadnej grupy dla aktualnego użytkownika.';
$string['note'] = 'Notatka';
$string['studentname'] = 'Nazwisko Studenta';
$string['loggedinas'] = 'Zalogowany jako';
$string['crondisallowed'] = 'procedura CRON próbowała uruchomić niedozwolony skrypt';
$string['register'] = 'Zarejestruj się jako Pracownik';
$string['register1'] = 'Zarejestruj się jako ';
$string['demomodule'] = 'Moduł Demonstracyjny';
$string['name'] = 'Nazwa';
$string['eassessmentmanagementsystem'] = 'System Zarządzaniem Oceną';
?>
