<?php
// This file is part of Rogo
//
// Rogo is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Rogo is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Rogo.  If not, see <http://www.gnu.org/licenses/>.

$string['error'] = 'Błąd';
$string['errormsg'] = 'Jeśli ten błąd się powtarza skontaktuj się z:';
$string['uploaderrormsg0'] = 'Błąd - ';
$string['uploaderrormsg1'] = 'Brak błędów - plik załadowano.';
$string['uploaderrormsg2'] = 'Rozmiar ładowanego pliku jest większy niż przewidziany w upload_max_filesize w php.ini.';
$string['uploaderrormsg3'] = 'Rozmiar ładowanego pliku jest większy niż przewidziany w MAX_FILE_SIZE w html-form.';
$string['uploaderrormsg4'] = 'Plik częściowo załadowany.';
$string['uploaderrormsg5'] = 'Nie załadowano pliku.';
$string['uploaderrormsg6'] = 'Brak tymczasowego katalogu.';
$string['uploaderrormsg7'] = 'Nieznany problem.';
$string['fatalerrormsg0'] = 'Błąd krytyczny';
$string['fatalerrormsg1'] = 'Brak wymaganej zmiennej GET.';
$string['fatalerrormsg2'] = 'Brak wymaganej zmiennej POST.';
$string['fatalerrormsg3'] = 'Brak wymaganej zmiennej REQUEST.';
$string['fatalerrorarray'] = 'Brak wymaganej zmiennej tablicowej.'; 
