<?php
// This file is part of Rogo
//
// Rogo is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Rogo is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Rogo.  If not, see <http://www.gnu.org/licenses/>.

$string['formative self-assessment'] = 'Formatywna samoocena';
$string['formative quiz'] = 'Test formatywny';
$string['progress test'] = 'Test postępów';
$string['summative exam'] = 'Egzamin końcowy';
$string['survey'] = 'Ankieta';
$string['osce station'] = 'Stacja OSCE';
$string['offline paper'] = 'Arkusz Offline';
$string['formative self-assessments'] = 'Formatywne samooceny';
$string['progress tests'] = 'Testy postępów';
$string['summative exams'] = 'Egzaminy końcowe';
$string['surveys'] = 'Ankiety';
$string['osce stations'] = 'Stacje OSCE';
$string['offline papers'] = 'Arkusze Offline';
$string['peer review'] = 'Recenzja wewnętrzna';
$string['description0'] = 'Quizy dla samooceny, zwykle dostępne dla studentów w każdej chwili.';
$string['description1'] = 'Zwykle używane w testach śródsemestralnych, gdy wyniki nie są podawane na koniec sprawdzianu.';
$string['description2'] = "Egzaminy dużej wagi, których stopnie składają się na ocenę końcową studenta.";
$string['description3'] = 'Ankiety używane do poznania poglądów i pozyskania informacji od studentów.';
$string['description4'] = 'Sprawdziany OSCE (Objective Structured Clinical Examination) używane w medycynie.';
$string['description5'] = 'Ten typ arkusza umożliwia załadowanie do Rogo ocen z testów offline.';
$string['description6'] = 'Generuje formularz pozwalający studentom oceniać się wzajemnie.';
?>