<?php
// This file is part of Rogo
//
// Rogo is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Rogo is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Rogo.  If not, see <http://www.gnu.org/licenses/>.

$string['passwordrequired'] = 'Wymagane hasło'; 
$string['specificpassword'] = 'Do tego arkusza przypisane jest specyficzne hasło.';
$string['enterpw'] = 'Wprowadź hasło dla tego arkusza';
$string['pwcontinue'] = 'Dalej'; 
$string['denied_location'] = 'Dostęp do tego arkusza nie jest dozwolony z tej lokalizacji.';
$string['error_time'] = 'Arkusz, który chcesz zobaczyć dostępny jest tylko pomiędzy %s i %s';
$string['notregistered'] = '%s %s (%s) nie jest zarejestrowany na <strong>%s</strong> w <strong>%s</strong>.';
$string['error_module'] = 'Nie ma tego arkusza w żadnym module.';
$string['error_metadata'] = 'Metadane użytkownika nie są zgodne <strong>%s: %s</strong>';
$string['alreadycompleted'] = 'Ocena została już zakończona w <strong>%s</strong>.';
?>