<?php
// This file is part of Rogo
//
// Rogo is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Rogo is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Rogo.  If not, see <http://www.gnu.org/licenses/>.

$string['anytype'] = '(każdy typ)';
$string['alltypes'] = 'wszystkie typy'; 
$string['branching'] = 'Rozgałęzienie';
$string['info'] = 'Blok informacji';
$string['keyword_based'] = 'Pytanie ze słowem kluczowym';
$string['keyword_based_short'] = 'Ze słowem kluczowym'; 
$string['random'] = 'Blok pytań losowanych';
$string['random_short'] = 'Losowe'; 
$string['calculation'] = 'Pytanie obliczeniowe';
$string['dichotomous'] = 'Pytanie rozróżniające';
$string['extmatch'] = 'Pytanie na dopasowanie';//rozbudowane pytanie na dopasowanie
$string['blank'] = 'Pytanie z luką';
$string['flash'] = 'Pytanie z interfejsem Flash';
$string['hotspot'] = 'Pytanie z miejscem aktywnym';//Hot spot
$string['labelling'] = 'Pytanie z etykietą graficzną';
$string['likert'] = 'Skala Likerta';
$string['matrix'] = 'Macierz';
$string['mcq'] = 'Pytanie wielokrotnego wyboru';
$string['mrq'] = 'Pytanie wielu odpowiedzi';
$string['rank'] = 'Pytanie na stopniowanie';
$string['sct'] = 'Test scenariusza';//Test zgodności ze scenariuszem
$string['sct_short'] = 'Test scenariusza'; 
$string['textbox'] = 'Pytanie półotwarte';
$string['true_false'] = 'Pytanie typu Prawda/Fałsz'; 
$string['area'] = 'Pytanie na obrys obszaru';
$string['enhancedcalc'] = 'Rozszerzone p. obliczeniowe';

$string['veryeasy'] = 'Bardzo Łatwe';
$string['easy'] = 'Łatwe';
$string['moderate'] = 'Średnio trudne';
$string['hard'] = 'Trudne';
$string['veryhard'] = 'Bardzo trudne';
$string['mean'] = 'Średnia';
$string['highest'] = 'Największe';
$string['high'] = 'Wysoka';
$string['intermediate'] = 'Umiarkowane';
$string['low'] = 'Niska';
?>