<?php
// This file is part of Rogo
//
// Rogo is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Rogo is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Rogo.  If not, see <http://www.gnu.org/licenses/>.

// Only translate the text on the right hand side.
$timezone_array = array(
  'Pacific/Samoa' => '(UTC-11:00) Samoa',
  'Pacific/Honolulu' => '(UTC-10:00) Hawaje',
  'America/Anchorage' => '(UTC-09:00) Alaska',
  'America/Los_Angeles' => '(UTC-08:00) Stany Zjednoczone i Kanada (czas pacyficzny)',
  'America/Denver' => '(UTC-07:00) Arizona',
  'America/Tegucigalpa' => '(UTC-06:00) Stany Zjednoczone i Kanada (czas centralny)',
  'America/New_York' => '(UTC-05:00) Stany Zjednoczone i Kanada (czas wschodni)',
  'America/Caracas' => '(UTC-04:30) Caracas',
  'America/Halifax' => '(UTC-04:00) Santiago',
  'America/St_Johns' => '(UTC-03:30) Nowa Funlandia',
  'America/Sao_Paulo' => '(UTC-03:00) Buenos Aires',
  'Atlantic/South_Georgia' => '(UTC-02:00) Środkowy Atlantyk',
  'Atlantic/Azores' => '(UTC-01:00) Azory',
  'Europe/London' => '(UTC) Dublin, Edynburg, Lizbona, Londyn',
  'Europe/Amsterdam' => '(UTC+01:00) Paryż, Berlin, Warszawa',
  'Europe/Athens' => '(UTC+02:00) Ateny, Bukareszt',
  'Africa/Johannesburg' => '(UTC+02:00) Cape Town, Johannesburg',
  'Asia/Kuwait' => '(UTC+03:00) Kuwejt, Rijad',
  'Asia/Tehran' => '(UTC+03:30) Teheran',
  'Europe/Moscow' => '(UTC+04:00) Moskwa, St. Petersburg, Wołgograd',
  'Asia/Kabul' => '(UTC+04:30) Kabul',
  'Asia/Karachi' => '(UTC+05:00) Islamabad, Karaczi',
  'Asia/Calcutta' => '(UTC+05:30) Kalkuta, Mumbaj, Nowe Delhi',
  'Asia/Dhaka' => '(UTC+06:00) Dhaka',
  'Asia/Rangoon' => '(UTC+06:30) Rangun',
  'Asia/Bangkok' => '(UTC+07:00) Bangkok, Hanoi, Dżakarta',
  'Asia/Kuala_Lumpur' => '(UTC+07:00) Bangkok, Hanoi, Dżakarta',
  'Asia/Hong_Kong' => '(UTC+08:00) Pekin, Chongqing, Hongkong',
  'Asia/Tokyo' => '(UTC+09:00) Osaka, Sapporo, Tokio',
  'Australia/Adelaide' => '(UTC+09:30) Adelajda',
  'Australia/Melbourne' => '(UTC+10:00) Canberra, Melbourne, Sydney',
  'Asia/Vladivostok' => '(UTC+11:00) Wyspy Salomona, Nowa Kaledonia',
  'Pacific/Auckland' => '(UTC+12:00) Auckland, Wellington'
);
?>