<?php
// This file is part of Rogo
//
// Rogo is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Rogo is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Rogo.  If not, see <http://www.gnu.org/licenses/>.

$string['genmsg'] = 'Szukaj wg. jednego lub wielu poniższych kryteriów';
$string['name'] = 'Nazwisko';
$string['username'] = 'Nazwa użytkownika';
$string['studentid'] = 'Numer legitymacji';
$string['module'] = 'Moduł';
$string['academicyear'] = 'Rok akademicki';
$string['advanced'] = 'Zaawansowane';
$string['students'] = 'Studenci';
$string['graduates'] = 'Absolwenci';
$string['leavers'] = 'Rezygnujący';//????
$string['leftuniversity'] = 'Opuścił uniwersytet';//????
$string['suspended'] = 'Zawieszeni';
$string['staff'] = 'Pracownicy';
$string['staffadmin'] = 'Pracownicy administracyjni';
$string['staffsysadmin'] = 'Pracownik (SysAdmin)';
$string['staffstudent'] = 'Pracownik i student'; 
$string['inactivestaff'] = 'Pracownicy nieaktywni';
$string['externalexaminers'] = 'Zewnętrzni egzaminatorzy';
$string['invigilators'] = 'Osoby nadzorujące';
$string['back'] = 'Wstecz';
$string['search'] = 'Szukaj';
$string['usertasks'] = 'Zadania użytkowników';
$string['viewuserfile'] = 'Teczka użytkownika';
$string['performsummary'] = 'Podsumowanie osiągnięć';
$string['createnewuser'] = 'Zdefiniuj użytkownika';
$string['emailuser'] = 'Wyślij Email do użytkownika';//???
$string['importusers'] = 'Importuj użytkowników';  
$string['importmodules'] = 'Importuj zapisy na moduł'; 
$string['anyyear'] = 'każdy rok';
$string['anymodule'] = '(każdy moduł)';
$string['title'] = 'Tytuł';
$string['year'] = 'Rok';
$string['course'] = 'Kurs';
$string['na'] = 'Brak';
$string['unknown'] = '&lt;nieznany&gt;';
$string['unknowndegree'] = '&lt;nieznany stopień&gt';
$string['mr'] = 'Pan';
$string['dr'] = 'Dr'; //cognate
$string['miss'] = 'Pani';
$string['mrs'] = '';
$string['ms'] = '';
$string['professor'] = 'Prof.';
$string['deleteuser'] = 'Usuń użytkownika';  
$string['clearltilinks'] = 'Clear LTI Links';
?>