<?php
// This file is part of Rogo
//
// Rogo is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Rogo is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Rogo.  If not, see <http://www.gnu.org/licenses/>.

$string['error'] = 'Error';
$string['errormsg'] = 'If you repeatedly get this error please contact:';
$string['uploaderrormsg0'] = 'Error - ';
$string['uploaderrormsg1'] = 'No problem, the file is uploaded.';
$string['uploaderrormsg2'] = 'The uploaded file was bigger then  upload_max_filesize in php.ini.';
$string['uploaderrormsg3'] = 'The uploaded file was bigger then MAX_FILE_SIZE in html-form.';
$string['uploaderrormsg4'] = 'File partialy uploaded.';
$string['uploaderrormsg5'] = 'No file was uploaded.';
$string['uploaderrormsg6'] = 'No temp directory.';
$string['uploaderrormsg7'] = 'Unknown problem.';
$string['fatalerrormsg0'] = 'Fatal Error';
$string['fatalerrormsg1'] = 'A mandatory GET variable is missing.';
$string['fatalerrormsg2'] = 'A mandatory POST variable is missing.';
$string['fatalerrormsg3'] = 'A mandatory REQUEST variable is missing.';
$string['fatalerrorarray'] = 'A mandatory Array variable is missing.';
