<?php
// This file is part of Rogo
//
// Rogo is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Rogo is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Rogo.  If not, see <http://www.gnu.org/licenses/>.

require '../lang/' . $language . '/include/question_types.inc';
require '../lang/' . $language . '/include/paper_types.inc';

$string['papertasks'] = 'Paper Tasks';
$string['testpreview'] = 'Test &amp; Preview';
$string['addquestionspaper'] = 'Add Questions to Paper';
$string['editproperties'] = 'Edit Properties';
$string['emailexternals'] = 'Email Externals';
$string['reports'] = 'Reports';
$string['mappedobjectives'] = 'Mapped Objectives';
$string['importmarks'] = 'Upload Marks';
$string['standardssetting'] = 'Standards Setting';
$string['importoscemarks'] = 'Import OSCE Marks';
$string['copypaper'] = 'Copy Paper';
$string['deletepaper'] = 'Delete Paper';
$string['retirepaper'] = 'Retire Paper';
$string['printhardcopy'] = 'Print Hardcopy version';
$string['importexport'] = 'Import/Export';
$string['export12'] = 'Export as QTI 1.2 format';
$string['exportraf'] = 'Export as Rog&#333; Assessment format';
$string['import'] = 'Import QTI format';
$string['importraf'] = 'Import Rog&#333; Assessment format';
$string['Continuous'] = 'Continuous';
$string['Page-break per question'] = 'Page-break per question';
$string['currentquestiontasks'] = 'Question Tasks';
$string['editquestion'] = 'Edit Question';
$string['previewquestion'] = 'Preview Question';
$string['information'] = 'Information';
$string['midexamclarification'] = 'Mid-Exam Clarification';
$string['copyontopaperx'] = 'Copy onto Paper X...';
$string['linktopaper'] = 'Link to paper';
$string['moveup'] = 'Move up';
$string['movedown'] = 'Move down';
$string['changescreenno'] = 'Change Screen No.';
$string['removefrompaper'] = 'Remove from Paper';
$string['setkillerquestion'] = 'Set Killer Question';
$string['unsetkillerquestion'] = 'Unset Killer Question';

$string['summativechecklist'] = 'Summative Checklist';
$string['session'] = 'Session';
$string['mismatch'] = 'Mismatch';
$string['examtime'] = 'Exam Time';
$string['incorrect'] = 'Incorrect';
$string['incomplete'] = 'Incomplete';
$string['duration'] = 'Duration';
$string['unset'] = 'Unset';
$string['computerlabs'] = 'Computer Labs';
$string['peerreviewed'] = 'Peer Reviewed';
$string['peerreviewes'] = 'Peer Reviews';
$string['externalreviews'] = 'External Reviews';
$string['standardsset'] = 'Standards Set';
$string['mapping'] = 'Mapping';

$string['questionbanktasks'] = 'Question Bank Tasks';
$string['questionsbytype'] = 'Questions by Type';
$string['questionsbyteam'] = 'Questions by Team';
$string['questionsbykeyword'] = 'Questions by Keyword';
$string['search'] = 'Search';
$string['createnewquestion'] = 'Create new Question';

$string['dates'] = 'Dates';
$string['to'] = 'to';
$string['course'] = 'Course';
$string['anycourse'] = '&lt;Any Course&gt;';
$string['module'] = 'Module';
$string['anymodule'] = '&lt;Any Module&gt;';
$string['cohort'] = 'Cohort';
$string['allcandidates'] = 'All candidates';
$string['top'] = 'Top';
$string['bottom'] = 'Bottom';
$string['year'] = 'Year';
$string['all'] = 'All';
$string['reviews'] = 'Reviews';
$string['internalpeerreview'] = 'Internal Peer Review';
$string['externalexaminers'] = 'External Examiners';
$string['sctresponses'] = 'SCT Responses/Reasons';
$string['classtotals'] = 'Class Totals';
$string['classtotalsexcel2003'] = 'Class Totals (Excel 2003)';
$string['classtotalscsv'] = 'Class Totals (CSV file)';
$string['textboxmarking'] = 'Textbox Marking';
$string['calculationquestions'] = 'Calculation Questions';
$string['markallquestions'] = 'Mark all questions';
$string['primarymarkbyquestion'] = 'Primary Mark by Question';
$string['selectpapersforremarking'] = 'Select Papers for Remarking';
$string['secondmarkbyquestion'] = 'Second Mark by Question';
$string['finalisemarks'] = 'Finalise Marks';
$string['frequencyanalysis'] = 'Frequency &amp; Discrimination (U-L) Analysis';
$string['learningobjectiveanalysis'] = 'Learning Objective Analysis';
$string['exportresponsescsvnum'] = 'Export responses as CSV file (raw)';
$string['exportresponsescsvtext'] = 'Export responses as CSV file (text)';
$string['exportbooleancsv'] = 'Export boolean responses as CSV file';
$string['exportmarkscsv'] = 'Export marks as CSV file';
$string['individualportfoliosheets'] = 'Individual Portfolio Sheets';
$string['exportratingscsv'] = 'Export ratings as CSV file';
$string['ReviewSummary1'] = 'Review Summary - means (HTML)';
$string['ReviewSummary2'] = 'Review Summary - percents (HTML)';
$string['ReviewSummary3'] = 'Review Summary';
$string['ReviewSummary4'] = 'Review Summary - means (CSV)';
$string['xhtml'] = 'XHTML';
$string['word2003format'] = 'Word 2003 format';
$string['rawdataxml'] = 'Raw data as XML file';
$string['rawdatacsv'] = 'Raw data as CSV file';
$string['itemanalysis'] = 'Item Analysis';
$string['cohortreports'] = 'Cohort Reports';
$string['exports'] = 'Exports';
$string['quantitativereports'] = 'Quantitative Reports';
$string['qualitativeanalysis'] = 'Qualitative Analysis';
$string['incabsentcandidates'] = 'inc. absent candidates';
$string['studentsonly'] = 'student attempts only';
$string['completedatasets'] = 'Show complete datasets only';
$string['anyyear'] = 'Any Year';
$string['tooltip_studentattempts'] = 'Uncheck to display staff and student attempts in Class Totals.';
$string['tooltip_daterange'] = 'Use dates to control the reporting window.';
 
$string['copyname'] = 'Copy Name';
$string['paperonly'] = 'Paper Only';
$string['paperandquestions'] = 'Paper and Questions';
$string['next'] = 'Next &gt;&gt;';
$string['reorderinfo'] = 'You can now reorder questions and screen breaks by dragging them to their new position';
$string['insertscreenbreak'] = 'Insert screen break';
$string['deletescreenbreak'] = 'Delete screen break';
$string['addscreenbreak'] = 'Add screen break';
$string['papers'] = 'Papers';
$string['questions'] = 'Questions';
$string['people'] = 'People';
$string['namewarning'] = 'This name is already being used by an existing paper!';
$string['type'] = 'Type';
?>