<?php
// This file is part of Rogo
//
// Rogo is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Rogo is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Rogo.  If not, see <http://www.gnu.org/licenses/>.

$string['genmsg'] = 'Search by any or all of the criteria below.';
$string['name'] = 'Name';
$string['username'] = 'Username';
$string['studentid'] = 'Student ID';
$string['module'] = 'Module';
$string['academicyear'] = 'Academic Year';
$string['advanced'] = 'Advanced';
$string['students'] = 'Students';
$string['graduates'] = 'Graduates';
$string['leavers'] = 'Leavers';
$string['leftuniversity'] = 'Left University';
$string['suspended'] = 'Suspended';
$string['staff'] = 'Staff';
$string['staffadmin'] = 'Staff (Admin)';
$string['staffsysadmin'] = 'Staff (SysAdmin)';
$string['staffstudent'] = 'Staff and Student';
$string['inactivestaff'] = 'Inactive Staff';
$string['externalexaminers'] = 'External Examiners';
$string['invigilators'] = 'Invigilators';
$string['back'] = 'Back';
$string['search'] = 'Search';
$string['usertasks'] = 'User Tasks';
$string['viewuserfile'] = 'View user file';
$string['performsummary'] = 'Performance Summary';
$string['createnewuser'] = 'Create New User';
$string['emailuser'] = 'Email User';
$string['importusers'] = 'Import Users';
$string['importmodules'] = 'Import Module Enrolments';
$string['anyyear'] = 'any year';
$string['anymodule'] = '(any module)';
$string['title'] = 'Title';
$string['year'] = 'Year';
$string['course'] = 'Course';
$string['na'] = 'n/a';
$string['unknown'] = '&lt;unknown&gt;';
$string['unknowndegree'] = '&lt;unknown degree&gt';
$string['mr'] = 'Mr';
$string['dr'] = 'Dr';
$string['miss'] = 'Miss';
$string['mrs'] = 'Mrs';
$string['ms'] = 'Ms';
$string['professor'] = 'Professor';
$string['deleteuser'] = 'Delete User';
$string['clearltilinks'] = 'Clear LTI Links';
?>