<?php
// This file is part of Rogo
//
// Rogo is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Rogo is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Rogo.  If not, see <http://www.gnu.org/licenses/>.

require '../lang/' . $language . '/include/months.inc';
require_once '../lang/' . $language . '/paper/new_paper2.php';

$string['moreinformation'] = 'More Information';
$string['viewdetails'] = 'View Details';
$string['debuginformation'] = 'Debug Information';
$string['loadingdebug'] = 'Loading Debug';
$string['intermediateformatdebug'] = 'Intermediate Format Debug';
$string['savingdebug'] = 'Saving Debug';
$string['generaldebuginfo'] = 'General Debug Info';
$string['addingtopaper'] = 'Adding to paper';
$string['params'] = 'Params';
$string['othherdebug'] = 'Other Debug';
$string['noquestions'] = 'No questions to load into Rogo';
$string['questiontables'] = 'Question Tables';
$string['questionsrow'] = 'questions row';
$string['optionsrows'] = 'options rows';
$string['newkeywords'] = 'new keywords';
$string['addingquestiondetails'] = 'adding question %d as display_pos = %d on screen %d';
?>