<?php
// This file is part of Rogō
//
// Rogō is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Rogō is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Rogō.  If not, see <http://www.gnu.org/licenses/>.

require '../lang/' . $language . '/include/months.inc';
require_once '../lang/' . $language . '/paper/new_paper2.php';

$string['moreinformation'] = 'Podrobnější informace';
$string['viewdetails'] = 'Zobrazit detaily';
$string['debuginformation'] = 'Debug informací';
$string['loadingdebug'] = 'Načíst Debug';
$string['intermediateformatdebug'] = 'Střední Debug formát';
$string['savingdebug'] = 'Uložit Debug';
$string['generaldebuginfo'] = 'Obecné Debug Info';
$string['addingtopaper'] = 'Přidat k dokumentu';
$string['params'] = 'Parametry';
$string['othherdebug'] = 'Jiný Debug';
$string['noquestions'] = 'Do Rogo nebyly načteny žádné úlohy';
$string['questiontables'] = 'Tabulky úloh';
$string['questionsrow'] = 'řádek úlohy';
$string['optionsrows'] = 'řádky voleb';
$string['newkeywords'] = 'nová klíčová slova';
$string['addingquestiondetails'] = 'přidat úlohu %d jako display_pos = %d do okna %d';
?>