<?php
// This file is part of Rogō
//
// Rogō is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Rogō is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Rogō.  If not, see <http://www.gnu.org/licenses/>.

$string['error'] = 'Chyba';
$string['errormsg'] = 'Pokud se tato chyba opakuje, kontaktujte, prosím:';
$string['uploaderrormsg0'] = 'CHYBA - ';
$string['uploaderrormsg1'] = 'Bez potíží, soubor je nahrán.';
$string['uploaderrormsg2'] = 'Nahrávaný soubor byl větší než upload_max_filesize v php.ini.';
$string['uploaderrormsg3'] = 'Nahrávaný soubor byl větší než MAX_FILE_SIZE v html-form.';
$string['uploaderrormsg4'] = 'Soubor byl nahrán pouze částečně.';
$string['uploaderrormsg5'] = 'Nebyl nahrán žádný soubor.';
$string['uploaderrormsg6'] = 'Žádný dočasný adresář.';
$string['uploaderrormsg7'] = 'Neznámý problém.';
$string['fatalerrormsg0'] = 'Velmi závažná chyba';
$string['fatalerrormsg1'] = 'Chybí povinná GET proměnná.';
$string['fatalerrormsg2'] = 'Chybí povinná POST proměnná.';
$string['fatalerrormsg3'] = 'Chybí povinná REQUEST proměnná.';
$string['fatalerrorarray'] = 'Chybí proměnná v povinném Poli.';
?>