<?php
// This file is part of Rogō
//
// Rogō is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Rogō is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Rogō.  If not, see <http://www.gnu.org/licenses/>.

$string['formative self-assessment'] = 'Cvičné sebehodnocení';
$string['formative quiz'] = 'Cvičný test';
$string['progress test'] = 'Průběžný test';
$string['summative exam'] = 'Sumativní zkouška';
$string['survey'] = 'Průzkum';
$string['osce station'] = 'Stanice OSCE';
$string['offline paper'] = 'Offline dokument';
$string['formative self-assessments'] = 'Cvičné sebehodnocení';
$string['progress tests'] = 'Průběžné testy';
$string['summative exams'] = 'Sumativní zkoušky';
$string['surveys'] = 'Průzkumy';
$string['osce stations'] = 'Stanice OSCE';
$string['offline papers'] = 'Offline dokumenty';
$string['peer review'] = 'Recenze';
$string['description0'] = 'Cvičné testy, jež by měly být studentovi přístupné kdykoliv.';
$string['description1'] = 'Běžně využívané ke zkoušení, komentáře nejsou na konci testu studentovi viditelné.';
$string['description2'] = 'Rozhodné testy jejichž hodnocení se podílí na celkové známce.';
$string['description3'] = 'Dotazník používaný k získání názorů a komentářů studentů.';
$string['description4'] = 'Předmětný OSCE (Objective Structured Clinical Examination) má využití v medicínských a zdravotnických oborech.';
$string['description5'] = 'Tento typ dokumentu umožňuje načtení známek z offline testu do Rogo.';
$string['description6'] = 'Generuje studentům formulář pro jejich vzájemné hodnocení.';
?>