<?php
// This file is part of Rogō
//
// Rogō is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Rogō is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Rogō.  If not, see <http://www.gnu.org/licenses/>.

$string['passwordrequired'] = 'Vyžadováno heslo';
$string['specificpassword'] = 'K tomuto dokumentu existuje konkrétní heslo.';
$string['enterpw'] = 'Zadejte, prosím, heslo k tomuto dokumentu';
$string['pwcontinue'] = 'Pokračovat';
$string['denied_location'] = 'Přístup k tomuto dokumentu není, z Vašeho aktuálního připojení, povolen. ';
$string['error_time'] = 'Dokument, u kterého se pokoušíte o přístup, je k dispozici pouze mezi %s a %s';
$string['notregistered'] = '%s %s (%s) není registrován k <strong>%s</strong> v <strong>%s</strong>.';
$string['error_module'] = 'Tento dokument není přiřazen k žádnému modulu.';
$string['error_metadata'] = 'Metadata uživatele neodpovídají <strong>%s: %s</strong>';
$string['alreadycompleted'] = 'Cvičení již proběhlo <strong>%s</strong>.';
?>
