<?php
// This file is part of Rogō
//
// Rogō is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Rogō is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Rogō.  If not, see <http://www.gnu.org/licenses/>.

$string['anytype'] = '(libovolný typ)';
$string['alltypes'] = 'Všechny typy';
$string['branching'] = 'Větvení';
$string['info'] = 'Informační blok';
$string['keyword_based'] = 'Úloha s klíčovým slovem';
$string['keyword_based_short'] = 'S klíčovým slovem';
$string['random'] = 'Blok náhodných úloh';
$string['random_short'] = 'Náhodný blok';
$string['calculation'] = 'Početní úloha';
$string['dichotomous'] = 'Dichotomická úloha';
$string['extmatch'] = 'Rozšířená shoda';
$string['blank'] = 'Doplňovací úloha';
$string['flash'] = 'Úloha využívající Flash';
$string['hotspot'] = 'Úloha s aktivním místem v obrázku';
$string['labelling'] = 'Umístění popisků';
$string['likert'] = 'Likertova stupnice';
$string['matrix'] = 'Matice';
$string['mcq'] = 'Výběr z možností';
$string['mrq'] = 'Výběr více správných odpovědí';
$string['rank'] = 'Pořadí';
$string['sct'] = 'Test shody se scénářem';
$string['sct_short'] = 'Shoda se scénářem';
$string['textbox'] = 'Textové pole';
$string['true_false'] = 'Pravda/Nepravda';
$string['area'] = 'Plocha';
$string['enhancedcalc'] = 'Rozšířená početní úloha';

$string['veryeasy'] = 'Velmi snadná';
$string['easy'] = 'Jednoduchá';
$string['moderate'] = 'Průměrná';
$string['hard'] = 'Nesnadná';
$string['veryhard'] = 'Velmi těžká';
$string['mean'] = 'Průměr';
$string['highest'] = 'Nejvyšší';
$string['high'] = 'Vysoké';
$string['intermediate'] = 'Střední';
$string['low'] = 'Nízké';
?>