<?php
// This file is part of Rogō
//
// Rogō is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Rogō is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Rogō.  If not, see <http://www.gnu.org/licenses/>.

// Only translate the text on the right hand side.
$timezone_array = array(
  'Pacific/Samoa' => '(UTC-11:00) Samoa',
  'Pacific/Honolulu' => '(UTC-10:00) Hawaii',
  'America/Anchorage' => '(UTC-09:00) Alaska',
  'America/Los_Angeles' => '(UTC-08:00) Pacific Time (US and Canada)',
  'America/Denver' => '(UTC-07:00) Arizona',
  'America/Tegucigalpa' => '(UTC-06:00) Central Time (US and Canada)',
  'America/New_York' => '(UTC-05:00) Eastern Time (US and Canada)',
  'America/Caracas' => '(UTC-04:30) Caracas',
  'America/Halifax' => '(UTC-04:00) Santiago',
  'America/St_Johns' => '(UTC-03:30) Newfoundland',
  'America/Sao_Paulo' => '(UTC-03:00) Buenos Aires',
  'Atlantic/South_Georgia' => '(UTC-02:00) Mid-Atlantic',
  'Atlantic/Azores' => '(UTC-01:00) Azores',
  'Europe/London' => '(UTC) Dublin, Edinburgh, Lisbon, London',
  'Europe/Amsterdam' => '(UTC+01:00) Amsterdam, Berlin, Stockholm, Praha',
  'Europe/Athens' => '(UTC+02:00) Athens, Bucharest',
  'Africa/Johannesburg' => '(UTC+02:00) Cape Town, Johannesburg',
  'Asia/Kuwait' => '(UTC+03:00) Kuwait, Riyadh',
  'Asia/Tehran' => '(UTC+03:30) Tehran',
  'Europe/Moscow' => '(UTC+04:00) Moscow, St. Petersburg, Volgograd',
  'Asia/Kabul' => '(UTC+04:30) Kabul',
  'Asia/Karachi' => '(UTC+05:00) Islamabad, Karachi',
  'Asia/Calcutta' => '(UTC+05:30) Kolkata, Mumbai, New Delhi',
  'Asia/Dhaka' => '(UTC+06:00) Dhaka',
  'Asia/Rangoon' => '(UTC+06:30) Yango (Rangoon)',
  'Asia/Bangkok' => '(UTC+07:00) Bangkok, Hanoi, Jakarta',
  'Asia/Hong_Kong' => '(UTC+08:00) Beijing, Chongqing, Hong Kong',
  'Asia/Tokyo' => '(UTC+09:00) Osaka, Sapporo, Tokyo',
  'Australia/Adelaide' => '(UTC+09:30) Adelaide',
  'Australia/Melbourne' => '(UTC+10:00) Canberra, Melbourne, Sydney',
  'Asia/Vladivostok' => '(UTC+11:00) Solomon Is., New Caledonia',
  'Pacific/Auckland' => '(UTC+12:00) Auckland, Wellington'
);
?>